theme: jekyll-theme-tactile

# Name of your blog (this will show up at the top of your page and in the RSS feed)
title: Colin Stephen

# Short description (goes below the title; it will also be used in the RSS feed)
description: Assistant Lecturer<br/> School of Computing, Electronics and Mathematics <br/> Coventry University

# Your name, as you want it to appear underneath each post and in the footer
author: Colin Stephen
